"""new table schema

Revision ID: 1f2d6989046e
Revises:
Create Date: 2023-01-25 11:40:07.863562

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "1f2d6989046e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "internetprotocol",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "address", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address", "lat", "lng", "country", "timestamp"),
    )
    op.create_index(
        "idx_lat_lng", "internetprotocol", ["lat", "lng"], unique=False
    )
    op.create_index(
        op.f("ix_internetprotocol_address"),
        "internetprotocol",
        ["address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_internetprotocol_country"),
        "internetprotocol",
        ["country"],
        unique=False,
    )
    op.create_table(
        "topic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_modified_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version"),
    )
    op.create_index(
        "idx_topic_version", "topic", ["name", "version"], unique=False
    )
    op.create_index(op.f("ix_topic_name"), "topic", ["name"], unique=False)
    op.create_table(
        "visitor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_id", sa.Integer(), nullable=True),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ip_id"],
            ["internetprotocol.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_visitor_ip_id"), "visitor", ["ip_id"], unique=False
    )
    op.create_index(
        op.f("ix_visitor_topic_id"), "visitor", ["topic_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_visitor_topic_id"), table_name="visitor")
    op.drop_index(op.f("ix_visitor_ip_id"), table_name="visitor")
    op.drop_table("visitor")
    op.drop_index(op.f("ix_topic_name"), table_name="topic")
    op.drop_index("idx_topic_version", table_name="topic")
    op.drop_table("topic")
    op.drop_index(
        op.f("ix_internetprotocol_country"), table_name="internetprotocol"
    )
    op.drop_index(
        op.f("ix_internetprotocol_address"), table_name="internetprotocol"
    )
    op.drop_index("idx_lat_lng", table_name="internetprotocol")
    op.drop_table("internetprotocol")
    # ### end Alembic commands ###
