"""add column created_at to table visitor again

Revision ID: c784daaf5d6d
Revises: a5bfed6cde22
Create Date: 2023-01-22 21:32:34.942709

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c784daaf5d6d"
down_revision = "a5bfed6cde22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "visitor", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visitor", "created_at")
    # ### end Alembic commands ###
